name: stud_advice
description: Frontend for Stud'Advice application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  logger: ^2.0.2+1
  get_it: ^7.6.4
  english_words: ^4.0.0
  intl: ^0.18.1
  country_picker: ^2.0.22
  dio: ^5.3.3
  flutter_typeahead: 4.8.0
  dropdown_search: ^5.0.6
  select_dialog: ^2.0.1
  connectivity_plus: ^5.0.1
  awesome_dialog: ^3.1.0
  jiffy: ^6.2.1
  search_choices: ^2.2.7
  get: ^4.6.6
  crypto: ^3.0.3
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  cloud_firestore: ^4.13.3
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.3
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.6
  get_storage: ^2.1.1
  infinite_scroll_pagination: ^4.0.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
          weight: 700


  assets:
    - assets/
    - assets/i18n/
    - assets/i18n/login_screen/
    - assets/i18n/settings_screen/
    - assets/i18n/home_page_screen/
    - assets/i18n/init_time_screen/
    - assets/i18n/legal_terms_screen/
    - assets/i18n/forgot_password_screen/
    - assets/i18n/register_options_screen/
    - assets/i18n/social_sign_in_controller/
    - assets/i18n/register_with_email_screen/
    - assets/i18n/register_user_information_screen/
    - assets/fonts/
    - assets/images/
    - assets/images/login/
    - assets/images/common/
    - assets/images/forgot_password/
    - assets/i18n/administratives_processes_screen/
    - assets/i18n/welcome_screen/
